name: Build Template (.NET)

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
        description: "Specifies the working directory for the SQL project."

env:
  BUILD_PATH: "DatabaseRelease"

jobs:
  build:
    name: Build SQL Project
    runs-on: windows-latest
    continue-on-error: false
    # environment: ${{ inputs.environment }}

    steps:
      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Build Database project
      - name: Build Database project
        id: dotnet_build
        run: |
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe' MyDotNetSqlProject.sqlproj /p:Configuration=Release /p:OutputPath=.\${{ env.BUILD_PATH }}
        working-directory: ${{ inputs.working_directory }}
      
      # Upload SQL Package Artifacts
      - name: Upload Build Artifacts
        id: build_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/${{ inputs.working_directory }}/${{ env.BUILD_PATH }}

