name: SQL Build Template (.NET)

on:
  workflow_call:
    inputs:
      build_artifact_name:
        required: true
        type: string
        description: "Specifies the name of the artifact to be downloaded."
      working_directory:
        required: true
        type: string
        description: "Specifies the working directory for the SQL project."

env:
  BUILD_PATH: "DatabaseRelease"

jobs:
  build:
    name: Build SQL Project
    runs-on: windows-latest
    continue-on-error: false
    # environment: ${{ inputs.environment }}

    steps:
      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3.1.0

      # Setup msbuild
      - name: Add msbuild to PATH
        id: msbuild_setup
        uses: microsoft/setup-msbuild@v1.1

      # Build Database project
      - name: Build Database project
        id: dotnet_build
        run: |
          msbuild.exe  MyDotNetSqlProject.sqlproj /p:Configuration=Release /p:OutputPath=.\${{ env.BUILD_PATH }}
        working-directory: ${{ inputs.working_directory }}

      # Upload SQL Package Artifacts
      - name: Upload Build Artifacts
        id: build_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.build_artifact_name }}
          path: ${{ github.workspace }}/${{ inputs.working_directory }}/${{ env.BUILD_PATH }}
