name: Deploy Template (.NET Core)

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: false
        type: string
        default: "6.0.x"
        description: "Specifies the .NET version."
      working_directory:
        required: true
        type: string
        description: "Specifies the working directory for the SQL project."
      project_name:
        required: true
        type: string
        description: "Specifies the name of the SQL project."
    secrets:
      azure_subscription_id:
        required: true
        description: "Specifies the subscription id of the deployment."
      azure_credentials:
        required: true
        description: "Specifies the azure credentials used for authentication."
      target_server_name:
        required: true
        description: "Specifies the target sql server name."
      target_database_name:
        required: true
        description: "Specifies the target sql database name."

env:
  BUILD_PATH: "DatabaseRelease"

jobs:
  build:
    name: Deploy SQL Project
    runs-on: ubuntu-latest
    continue-on-error: false
    # environment: ${{ inputs.environment }}

    steps:
      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        id: dotnet_setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      # Build Database project
      - name: Build Database project
        id: dotnet_build
        run: dotnet build /p:NetCoreBuild=true --configuration Release --output ./${{ env.BUILD_PATH }}
        working-directory: ${{ inputs.working_directory }}

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
          # enable-AzPSSession: true

      # Generate Azure Active Directory Token
      - name: Generate Azure Active Directory Token
        id: azure_access_token
        run: |
          echo "Set Azure Context"
          az account set -s "${{ secrets.azure_subscription_id }}"

          echo "Create Azure Access Token"
          ACCESS_TOKEN=$(az account get-access-token --scope "https://database.windows.net/.default" --query "accessToken" -o tsv)

          echo "Set secret value"
          echo "::add-mask::$ACCESS_TOKEN"
          echo "::set-output name=azureAccessToken::$ACCESS_TOKEN"

      # SQL Package Version
      - name: SQL Package Version
        id: sqlpackage_version
        run: sqlpackage /Version

      # SQL Package Deployment
      - name: SQL Package Deployment
        id: sqlpackage_deployment
        run: |
          sqlpackage /Action:Publish /SourceFile:"./${{ env.BUILD_PATH }}/${{ inputs.project_name }}.dacpac" /TargetServerName:"${{ secrets.target_server_name }}" /TargetDatabaseName:"${{ secrets.target_database_name }}" /AccessToken:"${{ steps.azure_access_token.outputs.azureAccessToken }}" /p:VerifyCollationCompatibility=true /p:VerifyDeployment=true /p:BlockOnPossibleDataLoss=true
        working-directory: ${{ inputs.working_directory }}

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: "agentazcliversion"
          inlineScript: |
            az logout
