name: Dev Deployment
on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/**"
      - "infra/**"

jobs:
  infra_validation_dev:
    uses: ./.github/workflows/infraValidationTemplate.yml
    name: "Validation of IaC templates - Dev"
    with:
      environment: "dev"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      azure_location_name: ${{ secrets.AZURE_LOCATION }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

  synapse_validation_dev:
    uses: ./.github/workflows/synapseValidationTemplate.yml
    name: "Validation of Synapse artifacts - Dev"
    with:
      environment: "dev"
      target_synapse_workspace_name: "data-auto-dev-synapse001"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

  sql_dotnet_build:
    uses: ./.github/workflows/buildDotNetTemplate.yml
    name: "Build SQL Project"
    with:
      build_artifact_name: buildDotNet
      working_directory: "code/MyDotNetSqlProject/MyDotNetSqlProject"

  sql_dotnetcore_build:
    uses: ./.github/workflows/buildDotNetCoreTemplate.yml
    name: "Build SQL Project"
    with:
      build_artifact_name: buildDotNetCore
      dotnet_version: "6.0.x"
      working_directory: "code/MyDotNetCoreSqlProject/"

  sql_dotnetcore_report_dev:
    uses: ./.github/workflows/sqlReportTemplate.yml
    name: "Report SQL Changes"
    needs: [infra_validation_dev, synapse_validation_dev, sql_dotnet_build, sql_dotnetcore_build]
    with:
      environment: "dev"
      build_artifact_name: "buildDotNetCore"
      report_artifact_name: "reportDotNetCore"
      working_directory: "code/MyDotNetCoreSqlProject/"
      project_name: "MyDotNetCoreSqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

  infra_deployment_dev:
    uses: ./.github/workflows/infraDeploymentTemplate.yml
    name: "Deployment of IaC templates - Dev"
    needs: [sql_dotnetcore_report_dev]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      azure_location_name: ${{ secrets.AZURE_LOCATION }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

  sql_dotnetcore_deployment_dev:
    uses: ./.github/workflows/sqlDeploymentTemplate.yml
    name: "Deploy SQL Changes"
    needs: [infra_deployment_dev]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
      build_artifact_name: "buildDotNetCore"
      working_directory: "code/MyDotNetCoreSqlProject/"
      project_name: "MyDotNetCoreSqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
