name: SQL - Test and Build

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - 'v*.*.*'

  # Run tests for any PRs.
  pull_request:
    branches:
      - main
    paths:
      - "code/**"
      - ".github/workflows/sql.yml"

jobs:
  sql:
    name: SQL
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        id: dotnet_setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      # Get SQL Package Version
      - name: Get SQL Package Version
        run: sqlpackage /version
      
      # Build .NET project
      - name: Build .NET project
        id: dotnet_build
        run: dotnet build "MyDatabase.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="./myDatabase"
        working-directory: "code/MyDatabase/"
