name: SQL - Test and Build

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - "v*.*.*"

  # Run tests for any PRs.
  pull_request:
    branches:
      - main
    paths:
      - "code/**"
      - ".github/workflows/sql.yml"

env:
  WORKING_DIRECTORY: "code/MySqlProject/"

jobs:
  sql_report:
    uses: ./.github/workflows/reportTemplate.yml
    name: "Report SQL Changes"
    with:
      dotnet_version: "6.0.x"
      working_directory: "code/MySqlProject/"
      project_name: "MySqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
  
  sql_deploy:
    uses: ./.github/workflows/deployTemplate.yml
    name: "Deploy SQL Changes"
    # needs: [sql_report]
    # if: github.event_name == 'push' || github.event_name == 'release'
    with:
      dotnet_version: "6.0.x"
      working_directory: "code/MySqlProject/"
      project_name: "MySqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
