name: SQL .NET - Test and Build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths:
      - "code/MyDotNetSqlProject/**"
      - ".github/workflows/**"

  pull_request:
    branches:
      - main
    paths:
      - "code/MyDotNetSqlProject/**"
      - ".github/workflows/**"

jobs:
  sql_build:
    uses: ./.github/workflows/buildDotNetTemplate.yml
    name: "Build SQL Project"
    with:
      build_artifact_name: buildDotNet
      working_directory: "code/MyDotNetSqlProject/MyDotNetSqlProject"
  
  sql_report_dev:
    uses: ./.github/workflows/sqlReportTemplate.yml
    name: "Report SQL Changes"
    needs: [sql_build]
    with:
      environment: "dev"
      build_artifact_name: "buildDotNet"
      report_artifact_name: "reportDotNet"
      working_directory: "code/MyDotNetSqlProject/MyDotNetSqlProject"
      project_name: "MyDotNetSqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
  
  sql_deploy_dev:
    uses: ./.github/workflows/sqlDeploymentTemplate.yml
    name: "Deploy SQL Changes"
    needs: [sql_report_dev]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
      build_artifact_name: "buildDotNet"
      working_directory: "code/MyDotNetSqlProject/MyDotNetSqlProject"
      project_name: "MyDotNetSqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
