name: SQL .NET - Test and Build

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - "v*.*.*"

  # Run tests for any PRs.
  pull_request:
    branches:
      - main
    paths:
      - "code/MyDotNetSqlProject/**"
      - ".github/workflows/sqlDotNet.yml"

jobs:
  sql_build:
    uses: ./.github/workflows/buildDotNetTemplate.yml
    name: "Build SQL Project"
    with:
      build_artifact_name: buildDotNet
      working_directory: "code/MyDotNetSqlProject/MyDotNetSqlProject"
  
  sql_report:
    uses: ./.github/workflows/reportTemplate.yml
    name: "Report SQL Changes"
    needs: [sql_build]
    with:
      build_artifact_name: buildDotNet
      report_artifact_name: reportDotNet
      working_directory: "code/MyDotNetSqlProject/MyDotNetSqlProject"
      project_name: "MyDotNetSqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
  
  sql_deploy:
    uses: ./.github/workflows/deployTemplate.yml
    name: "Deploy SQL Changes"
    needs: [sql_build, sql_report]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      build_artifact_name: buildDotNet
      working_directory: "code/MyDotNetSqlProject/MyDotNetSqlProject"
      project_name: "MyDotNetSqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
