name: SQL Report Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      build_artifact_name:
        required: true
        type: string
        description: "Specifies the name of the artifact to be downloaded."
      report_artifact_name:
        required: false
        default: report
        type: string
        description: "Specifies the name of the report artifact to be created."
      working_directory:
        required: true
        type: string
        description: "Specifies the working directory for the SQL project."
      project_name:
        required: true
        type: string
        description: "Specifies the name of the SQL project."
    secrets:
      azure_subscription_id:
        required: true
        description: "Specifies the subscription id of the deployment."
      azure_credentials:
        required: true
        description: "Specifies the azure credentials used for authentication."
      target_server_name:
        required: true
        description: "Specifies the target sql server name."
      target_database_name:
        required: true
        description: "Specifies the target sql database name."

env:
  BUILD_PATH: "DatabaseRelease"
  OUTPUT_PATH: "Report"

jobs:
  build:
    name: Report SQL Project Changes
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: ${{ inputs.environment }}

    steps:
      # Download Build Artifact
      - name: Download Build Artifact
        id: artifact_download
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build_artifact_name }}
          path: ${{ github.workspace }}/${{ inputs.working_directory }}/${{ env.BUILD_PATH }}

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
          # enable-AzPSSession: true

      # Generate Azure Active Directory Token
      - name: Generate Azure Active Directory Token
        id: azure_access_token
        run: |
          echo "Set Azure Context"
          az account set -s "${{ secrets.azure_subscription_id }}"

          echo "Create Azure Access Token"
          ACCESS_TOKEN=$(az account get-access-token --scope "https://database.windows.net/.default" --query "accessToken" -o tsv)

          echo "Set secret value"
          echo "::add-mask::$ACCESS_TOKEN"
          echo "::set-output name=azureAccessToken::$ACCESS_TOKEN"

      # Create Output Directory
      - name: Create Output Directory
        id: output_directory
        run: mkdir ${{ env.OUTPUT_PATH }}
        working-directory: ${{ inputs.working_directory }}

      # SQL Package Version
      - name: SQL Package Version
        id: sqlpackage_version
        run: sqlpackage /Version

      # SQL Package Deployment Report
      - name: SQL Package Deployment Report
        id: sqlpackage_deployreport
        run: |
          sqlpackage /Action:DeployReport /SourceFile:"${{steps.artifact_download.outputs.download-path}}/${{ inputs.project_name }}.dacpac" /TargetServerName:"${{ secrets.target_server_name }}" /TargetDatabaseName:"${{ secrets.target_database_name }}" /OutputPath:"./${{ env.OUTPUT_PATH }}/deployReport.xml" /AccessToken:"${{ steps.azure_access_token.outputs.azureAccessToken }}" /p:VerifyCollationCompatibility=true /p:VerifyDeployment=true
        working-directory: ${{ inputs.working_directory }}

      # SQL Package Deployment Script
      - name: SQL Package Deployment Script
        id: sqlpackage_script
        run: |
          sqlpackage /Action:Script /SourceFile:"${{steps.artifact_download.outputs.download-path}}/${{ inputs.project_name }}.dacpac" /TargetServerName:"${{ secrets.target_server_name }}" /TargetDatabaseName:"${{ secrets.target_database_name }}" /OutputPath:"./${{ env.OUTPUT_PATH }}/deployScript.sql" /AccessToken:"${{ steps.azure_access_token.outputs.azureAccessToken }}" /p:VerifyCollationCompatibility=true /p:VerifyDeployment=true
        working-directory: ${{ inputs.working_directory }}

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: "agentazcliversion"
          inlineScript: |
            az logout

      # Upload SQL Package Results
      - name: Upload SQL Package Results
        id: sqlpackage_results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.report_artifact_name }}
          path: ${{ github.workspace }}/${{ inputs.working_directory }}/${{ env.OUTPUT_PATH }}
