name: Test Deployment
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths:
      - ".github/workflows/**"
      - "code/**"
      - "infra/**"
      - "data-auto-dev-synapse001/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/**"
      - "infra/**"
      - "data-auto-dev-synapse001/**"

jobs:
  infra_validation_tst:
    uses: ./.github/workflows/infraValidationTemplate.yml
    name: "Validation of IaC templates - Tst"
    with:
      environment: "tst"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      azure_location_name: ${{ secrets.AZURE_LOCATION }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

  synapse_validation_tst:
    uses: ./.github/workflows/synapseValidationTemplate.yml
    name: "Validation of Synapse artifacts - Tst"
    with:
      environment: "tst"
      target_synapse_workspace_name: "data-auto-tst-synapse001"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

  sql_dotnet_build:
    uses: ./.github/workflows/buildDotNetTemplate.yml
    name: "Build SQL Project"
    with:
      build_artifact_name: buildDotNet
      working_directory: "code/MyDotNetSqlProject/MyDotNetSqlProject"

  sql_dotnetcore_build:
    uses: ./.github/workflows/buildDotNetCoreTemplate.yml
    name: "Build SQL Project"
    with:
      build_artifact_name: buildDotNetCore
      dotnet_version: "6.0.x"
      working_directory: "code/MyDotNetCoreSqlProject/"

  sql_dotnetcore_report_tst:
    uses: ./.github/workflows/sqlReportTemplate.yml
    name: "Report SQL Changes"
    needs: [infra_validation_tst, synapse_validation_tst, sql_dotnet_build, sql_dotnetcore_build]
    with:
      environment: "tst"
      build_artifact_name: "buildDotNetCore"
      report_artifact_name: "reportDotNetCore"
      working_directory: "code/MyDotNetCoreSqlProject/"
      project_name: "MyDotNetCoreSqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

  infra_deployment_tst:
    uses: ./.github/workflows/infraDeploymentTemplate.yml
    name: "Deployment of IaC templates - Tst"
    needs: [sql_dotnetcore_report_tst]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "tst"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      azure_location_name: ${{ secrets.AZURE_LOCATION }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

  synapse_deployment_tst:
    uses: ./.github/workflows/synapseDeploymentTemplate.yml
    name: "Deployment of Synapse artifacts - Test"
    needs: [infra_deployment_tst]
    if: github.event_name == 'push'
    with:
      environment: "tst"
      source_synapse_workspace_name: "data-auto-dev-synapse001"
      target_synapse_workspace_name: "data-auto-tst-synapse001"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

  sql_dotnetcore_deployment_tst:
    uses: ./.github/workflows/sqlDeploymentTemplate.yml
    name: "Deploy SQL Changes"
    needs: [synapse_deployment_tst]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "tst"
      build_artifact_name: "buildDotNetCore"
      working_directory: "code/MyDotNetCoreSqlProject/"
      project_name: "MyDotNetCoreSqlProject"
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      target_server_name: ${{ secrets.SQL_SERVER_NAME }}
      target_database_name: ${{ secrets.SQL_DATABASE_NAME }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
